CREATE OR REPLACE PROCEDURE PESSOA_FISICA_CADASTRA (
	:CPF IN PESSOA_FISICA.CPF%TYPE,
	:DATANASC IN PESSOA_FISICA.DATANASC%TYPE,
	:NOME IN PESSOA_FISICA.NOME%TYPE,
	:SOBRENOME IN PESSOA_FISICA.SOBRENOME%TYPE,
	:CEP IN ENDERECO.CEP%TYPE,
	:BAIRRO IN ENDERECO.BAIRRO%TYPE,
	:CIDADE IN ENDERECO.CIDADE%TYPE,
	:LOGRADOURO IN ENDERECO.LOGRADOURO%TYPE,
	:COMPLEMENTO IN ENDERECO.COMPLEMENTO%TYPE,
	:NUMERO IN ENDERECO.NUMERO%TYPE,
	:UFCOMPLETO IN ENDERECO.UFCOMPLETO%TYPE
	
) AS
DECLARE
  enderecoID int;
  pessoaID int;
BEGIN

	INSERT INTO 
		PESSOA_FISICA
		( 
		CPF, 
		DATANASC, 
		NOME, 
		SOBRENOME, 
		CEP
		) 
	VALUES
		(
		:CPF, 
		:DATANASC, 
		:NOME, 
		:SOBRENOME);
	
	
	INSERT INTO 
		ENDERECO
		(
		CEP,
		BAIRRO,
		CIDADE,
		LOGRADOURO,
		COMPLEMENTO,
		NUMERO,
		UFCOMPLETO
		)
	VALUES
		(
		:CEP,
		:BAIRRO,
		:CIDADE,
		:LOGRADOURO,
		:COMPLEMENTO,
		:NUMERO,
		:UFCOMPLETO
		);
	
	SELECT ENDERECOSEQ.currval into enderecoID FROM dual;
	SELECT PESSOA_FISICASEQ.currval into pessoaID FROM dual;
	
	UPDATE
		PESSOA_FISICA
	SET
		IDENDERECO = enderecoID
	WHERE
		ID = pessoaID;
	
	
	COMMIT;
	
END PESSOA_FISICA_CADASTRA;