CREATE OR REPLACE PROCEDURE PESSOA_JURIDICA_ALTERA (
	:ID  IN PESSOA_JURIDICA.ID%TYPE,
	:CNPJ IN PESSOA_JURIDICA.CNPJ%TYPE,
	:NOMEFANTASIA IN PESSOA_JURIDICA.NOMEFANTASIA%TYPE,
	:RAZAOSOCIAL IN PESSOA_JURIDICA.RAZAOSOCIAL%TYPE,
	:CEP IN ENDERECO.CEP%TYPE,
	:BAIRRO IN ENDERECO.BAIRRO%TYPE,
	:CIDADE IN ENDERECO.CIDADE%TYPE,
	:LOGRADOURO IN ENDERECO.LOGRADOURO%TYPE,
	:COMPLEMENTO IN ENDERECO.COMPLEMENTO%TYPE,
	:NUMERO IN ENDERECO.NUMERO%TYPE,
	:UF IN ENDERECO.UF%TYPE
	
) AS
DECLARE
  enderecoID int;
  pessoaID int;
BEGIN

	UPDATE
		PESSOA_JURIDICA
	SET
		CNPJ = :CNPJ, 
		NOMEFANTASIA = :NOMEFANTASIA, 
		RAZAOSOCIAL = :RAZAOSOCIAL
	WHERE
		ID = :ID
	;
		
	SELECT IDENDERECO into enderecoID FROM PESSOA_JURIDICA;
	
	UPDATE
		ENDERECO
	SET
		
		CEP = :CEP,
		BAIRRO = :BAIRRO,
		CIDADE = :CIDADE,
		LOGRADOURO = :LOGRADOURO,
		COMPLEMENTO = :COMPLEMENTO,
		NUMERO = :NUMERO,
		UFCOMPLETO = :UFCOMPLETO
	WHERE
		IDENDERECO = enderecoID
	;
		(
		:CEP,
		:BAIRRO,
		:CIDADE,
		:LOGRADOURO,
		:COMPLEMENTO,
		:NUMERO,
		:UF
		);
	
	
	SELECT PESSOA_FISICASEQ.currval into pessoaID FROM dual;
	
	UPDATE
		PESSOA_FISICA
	SET
		IDENDERECO = enderecoID
	WHERE
		ID = pessoaID;
	
	COMMIT;
	
	
	
END PESSOA_JURIDICA_ALTERA;