CREATE OR REPLACE PROCEDURE PESSOA_FISICA_ALTERA (
	:ID  IN PESSOA_FISICA.ID%TYPE,
	:CPF IN PESSOA_FISICA.CPF%TYPE,
	:DATANASC IN PESSOA_FISICA.DATANASC%TYPE,
	:NOME IN PESSOA_FISICA.NOME%TYPE,
	:SOBRENOME IN PESSOA_FISICA.SOBRENOME%TYPE,
	:CEP IN ENDERECO.CEP%TYPE,
	:BAIRRO IN ENDERECO.BAIRRO%TYPE,
	:CIDADE IN ENDERECO.CIDADE%TYPE,
	:LOGRADOURO IN ENDERECO.LOGRADOURO%TYPE,
	:COMPLEMENTO IN ENDERECO.COMPLEMENTO%TYPE,
	:NUMERO IN ENDERECO.NUMERO%TYPE,
	:UFCOMPLETO IN ENDERECO.UFCOMPLETO%TYPE
	
) AS
DECLARE
  enderecoID int;
  pessoaID int;
BEGIN

	UPDATE
		PESSOA_FISICA
	SET
		
		CPF = :CPF, 
		DATANASC = :DATANASC, 
		NOME = :NOME, 
		SOBRENOME = :SOBRENOME
	WHERE
		ID = :ID
	;
		
	SELECT IDENDERECO into enderecoID FROM PESSOA_FISICA;
	
	UPDATE
		ENDERECO
	SET
		
		CEP = :CEP,
		BAIRRO = :BAIRRO,
		CIDADE = :CIDADE,
		LOGRADOURO = :LOGRADOURO,
		COMPLEMENTO = :COMPLEMENTO,
		NUMERO = :NUMERO,
		UFCOMPLETO = :UFCOMPLETO
	WHERE
		IDENDERECO = enderecoID
	;
		(
		:CEP,
		:BAIRRO,
		:CIDADE,
		:LOGRADOURO,
		:COMPLEMENTO,
		:NUMERO,
		:UFCOMPLETO
		);
	
	
	SELECT PESSOA_FISICASEQ.currval into pessoaID FROM dual;
	
	UPDATE
		PESSOA_FISICA
	SET
		IDENDERECO = enderecoID
	WHERE
		ID = pessoaID;
	
	
	COMMIT;
	
END PESSOA_FISICA_CADASTRA;