CREATE OR REPLACE PROCEDURE PESSOA_FISICA_DADOS (v_id PESSOA_JURIDICA.ID%TYPE) AS 
BEGIN
	SELECT 
		PF.ID, 
		PF.CPF, 
		PF.DATANASC, 
		PF.NOME, 
		PF.SOBRENOME, 
		PF.CEP, 
		E.BAIRRO,
		E.CIDADE,
		E.LOGRADOURO,
		E.COMPLEMENTO,
		E.NUMERO,
		E.UFCOMPLETO
	FROM 
		PESSOA_FISICA PF
		JOIN
		ENDERECO E
			ON
			PF.IDENDERECO = E.IDENDERECO
	WHERE
		PF.ID = v_id
	;
    
END PESSOA_FISICA_LISTA;