CREATE OR REPLACE PROCEDURE PESSOA_JURIDICA_LISTA AS 
BEGIN
  SELECT 
    PJ.ID, 
    PJ.CPF, 
    PJ.DATANASC, 
    PJ.NOME, 
    PJ.SOBRENOME, 
    PJ.CEP, 
    E.BAIRRO,
    E.CIDADE,
    E.LOGRADOURO,
    E.COMPLEMENTO,
    E.NUMERO,
    E.UFCOMPLETO
  FROM 
    PESSOA_JURIDICA PJ
    JOIN
    ENDERECO E
      ON
        PJ.IDENDERECO = E.IDENDERECO;
    
END PESSOA_FISICA_LISTA;